micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    keyManager:
      address: ${IP_HOST:localhost}:${PORT_HOST:50051}
      plaintext: true
      max-retry-attempts: 5
